project:
  render:
    - ../../acknowledgements.qmd
    - ../../preface.qmd
    - ../../abstract.qmd
    - ../../dedication.qmd

bibliography: bibliography.bib

format:
  latex:
    template: template.tex
    cite-method: biblatex
