project:
  type: book
  pre-render: quarto render _prelims
  post-render: ./_prelims/cleanup.bash

book:
  title: "quarto-thesis"
  author: "Norah Jones"
  date: "1/22/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

abbrs:
  TCP: Transmission Control Protocol
  IP: Internet Protocol
  JSON: JavaScript Object Notation

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    realdocumentclass: reedthesis
    template: template.tex
    template-partials:
      - doc-class.tex
