project:
  type: book
  pre-render: quarto render _prelims
  post-render: ./_prelims/cleanup.bash

book:
  title: "quarto-thesis"
  author: "Sam Gauck"
  date: "May 2025"
  date-format: "MMMM YYYY"
  chapters:
    # All books must have an index.qmd file. See https://github.com/quarto-dev/quarto-cli/issues/2556
    # If the file is empty, it produces an empty chapter.
    # Therefore, we put our introduction in index.qmd
    - index.qmd
    - summary.qmd
  appendices:
    - appendix.qmd

bibliography: references.bib

filters:
  - quarto
  - remove-appendix-part.lua

abbrs:
  TCP: Transmission Control Protocol
  IP: Internet Protocol
  JSON: JavaScript Object Notation
division: Mathematics and Natural Sciences
department: Computer Science
advisor: Erica Blum

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    realdocumentclass: reedthesis
    template: template.tex
    template-partials:
      - doc-class.tex
      - biblio.tex
    cite-method: biblatex
