project:
  type: book
  pre-render: quarto render _prelims
  post-render: ./_prelims/cleanup.bash

book:
  title: "quarto-thesis"
  author: "Norah Jones"
  date: "1/22/2025"
  chapters:
    # All books must have an index.qmd file. See https://github.com/quarto-dev/quarto-cli/issues/2556
    # If the file is empty, it produces an empty chapter.
    # Therefore, we put our introduction in index.qmd
    - index.qmd
    - summary.qmd

bibliography: references.bib

abbrs:
  TCP: Transmission Control Protocol
  IP: Internet Protocol
  JSON: JavaScript Object Notation

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    realdocumentclass: reedthesis
    template: template.tex
    template-partials:
      - doc-class.tex
      - biblio.tex
    cite-method: biblatex
