name: Build latest thesis draft

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build with Pandoc/LaTeX (via Nix)
        run: nix build .#thesis
        # Create a link to the output file **with the .pdf extension**
        # Otherwise the artifact has no extension when downloaded (because `result` has no extension)
      - name: Rename output file
        run: |
          ln -s result thesis.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis.pdf
          path: ./thesis.pdf
          if-no-files-found: error
